
packageExtensions:
  "@storybook/core-server@9.1.3":
    dependencies:
      storybook: 9.1.3
  storybook@9.1.3:
    dependencies:
      storybook: 9.1.3
      "@storybook/global": ^5.0.0

pnpMode: loose
nodeLinker: node-modules
